#!/usr/bin/env python3
"""Collect a read-only repository inventory for convergence work."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from itertools import islice
from pathlib import Path
from typing import Any


SKIPPED_DIRECTORIES = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "vendor",
}
INSTRUCTION_NAMES = {"AGENTS.md", "CLAUDE.md"}
CONFIG_NAMES = {
    "Makefile",
    "package.json",
    "pyproject.toml",
    "requirements.txt",
    "setup.cfg",
    "tox.ini",
    "tsconfig.json",
}
TEXT_SUFFIXES = {
    ".css",
    ".go",
    ".html",
    ".java",
    ".js",
    ".json",
    ".jsx",
    ".md",
    ".py",
    ".rb",
    ".rs",
    ".sh",
    ".sql",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".yaml",
    ".yml",
}
GENERATED_MARKERS = (
    "auto-generated",
    "autogenerated",
    "do not edit",
    "generated file",
    "generated;",
)
COMMENT_PREFIXES = {
    ".css": ("/*",),
    ".go": ("//", "/*"),
    ".html": ("<!--",),
    ".java": ("//", "/*"),
    ".js": ("//", "/*"),
    ".jsx": ("//", "/*"),
    ".md": ("<!--",),
    ".py": ("#",),
    ".rb": ("#",),
    ".rs": ("//", "/*"),
    ".sh": ("#",),
    ".sql": ("--", "/*"),
    ".ts": ("//", "/*"),
    ".tsx": ("//", "/*"),
    ".yaml": ("#",),
    ".yml": ("#",),
}


def relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def repository_files(root: Path) -> tuple[list[Path], list[str]]:
    files: list[Path] = []
    skipped_symlinks: list[str] = []
    for path in sorted(root.rglob("*")):
        parts = path.relative_to(root).parts
        if any(part in SKIPPED_DIRECTORIES for part in parts):
            continue
        if path.is_symlink():
            skipped_symlinks.append(relative(path, root))
            continue
        if path.is_file():
            files.append(path)
    return files, skipped_symlinks


def has_part(path: Path, *names: str) -> bool:
    lowered = {part.lower() for part in path.parts}
    return any(name in lowered for name in names)


def looks_like_test(path: Path) -> bool:
    name = path.name.lower()
    return (
        has_part(path, "test", "tests", "spec", "specs", "__tests__")
        or name.startswith("test_")
        or ".test." in name
        or ".spec." in name
    )


def generated_file(path: Path) -> bool:
    if path.suffix.lower() not in TEXT_SUFFIXES and path.name != "Makefile":
        return False
    try:
        with path.open(encoding="utf-8", errors="ignore") as handle:
            lines = [line.strip().lower() for line in islice(handle, 8) if line.strip()]
    except OSError:
        return False
    prefixes = COMMENT_PREFIXES.get(path.suffix.lower(), ("#",))
    return any(
        line.startswith(prefixes) and any(marker in line for marker in GENERATED_MARKERS)
        for line in lines
    )


def explicit_commands(root: Path) -> list[str]:
    commands: set[str] = set()
    package_json = root / "package.json"
    if package_json.is_file():
        try:
            scripts = json.loads(package_json.read_text(encoding="utf-8")).get("scripts", {})
            if isinstance(scripts, dict):
                commands.update(f"npm run {name}" for name in scripts if isinstance(name, str))
        except (OSError, json.JSONDecodeError, AttributeError):
            pass

    makefile = root / "Makefile"
    if makefile.is_file():
        try:
            for line in makefile.read_text(encoding="utf-8", errors="ignore").splitlines():
                match = re.match(r"^([A-Za-z0-9_.-]+):(?:\s|$)", line)
                if match and not match.group(1).startswith("."):
                    commands.add(f"make {match.group(1)}")
        except OSError:
            pass
    return sorted(commands)


def git_evidence(root: Path) -> dict[str, Any]:
    probe = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
        text=True,
        capture_output=True,
        check=False,
    )
    if probe.returncode != 0:
        return {"is_repository": False, "root": None, "status": []}

    status = subprocess.run(
        ["git", "-C", str(root), "status", "--short", "--branch"],
        text=True,
        capture_output=True,
        check=False,
    )
    return {
        "is_repository": True,
        "root": probe.stdout.strip(),
        "status": status.stdout.splitlines() if status.returncode == 0 else [],
    }


def collect_evidence(root: Path) -> dict[str, Any]:
    root = root.expanduser().resolve()
    if not root.is_dir():
        raise ValueError(f"repository root is not a directory: {root}")

    files, skipped_symlinks = repository_files(root)
    rel = {path: relative(path, root) for path in files}

    inventory = {
        "instruction_files": sorted(value for path, value in rel.items() if path.name in INSTRUCTION_NAMES),
        "domain_files": sorted(value for path, value in rel.items() if path.name == "CONTEXT.md"),
        "adr_files": sorted(
            value
            for path, value in rel.items()
            if path.suffix.lower() == ".md" and has_part(path.relative_to(root), "adr", "adrs")
        ),
        "markdown_files": sorted(value for path, value in rel.items() if path.suffix.lower() == ".md"),
        "test_files": sorted(value for path, value in rel.items() if looks_like_test(path.relative_to(root))),
        "config_files": sorted(
            value
            for path, value in rel.items()
            if path.name in CONFIG_NAMES or has_part(path.relative_to(root), "config", "configs")
        ),
        "schema_files": sorted(
            value for path, value in rel.items() if has_part(path.relative_to(root), "schema", "schemas")
        ),
        "migration_files": sorted(
            value for path, value in rel.items() if has_part(path.relative_to(root), "migration", "migrations")
        ),
        "generated_files": sorted(value for path, value in rel.items() if generated_file(path)),
    }

    return {
        "schema_version": 1,
        "root": str(root),
        "git": git_evidence(root),
        "coverage": {
            "files_seen": len(files),
            "skipped_symlinks": sorted(skipped_symlinks),
        },
        "inventory": inventory,
        "available_commands": explicit_commands(root),
        "limitations": [
            "Inventory is evidence, not a decision about canonical ownership or correctness.",
            "Generated-file detection uses header markers and may miss unmarked artifacts.",
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True, help="Repository root to inspect")
    parser.add_argument("--pretty", action="store_true", help="Indent JSON output")
    args = parser.parse_args()

    try:
        evidence = collect_evidence(args.root)
    except ValueError as error:
        parser.error(str(error))
    print(json.dumps(evidence, ensure_ascii=False, indent=2 if args.pretty else None, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
